### ISSUE TITLE
Polytexnic appears to be passing nokogiri nil when processing codelistings

### ISSUE THREAD

**Issue by forsakendaemon** [softcover/polytexnic#127]
Iam putting this here even 'though it's in the context of Softcover because it seems to be an issue in Polytexnic, although if it's a Softcover issue then I'm happy to recreate it there.

Steps to reproduce:
1. Fresh install of Softcover and its dependencies
2. Create a project with a single chapter.md referenced in Book.txt with the following content:
```\begin{codelisting}
\codecaption{Caption}
\end{codelisting}
```
3. run `sc build:html`

Output text:
```Building HTML...
Traceback (most recent call last):
        21: from /usr/local/bin/sc:23:in `<main>'
        20: from /usr/local/bin/sc:23:in `load'
        19: from /var/lib/gems/2.7.0/gems/softcover-1.8.1/bin/sc:4:in `<top (required)>'
        18: from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        17: from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        16: from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        15: from /var/lib/gems/2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        14: from /var/lib/gems/2.7.0/gems/softcover-1.8.1/lib/softcover/cli.rb:56:in `block (2 levels) in <class:CLI>'
        13: from /var/lib/gems/2.7.0/gems/softcover-1.8.1/lib/softcover/commands/build.rb:12:in `for_format'
        12: from /var/lib/gems/2.7.0/gems/softcover-1.8.1/lib/softcover/builder.rb:18:in `build!'
        11: from /var/lib/gems/2.7.0/gems/softcover-1.8.1/lib/softcover/builders/html.rb:43:in `build'
        10: from /var/lib/gems/2.7.0/gems/softcover-1.8.1/lib/softcover/builders/html.rb:123:in `converted_html'
         9: from /var/lib/gems/2.7.0/gems/polytexnic-1.8.0/lib/polytexnic.rb:91:in `to_html'
         8: from /var/lib/gems/2.7.0/gems/polytexnic-1.8.0/lib/polytexnic/postprocessor.rb:16:in `postprocess'
         7: from /var/lib/gems/2.7.0/gems/polytexnic-1.8.0/lib/polytexnic/postprocessors/html.rb:46:in `xml_to_html'
         6: from /var/lib/gems/2.7.0/gems/polytexnic-1.8.0/lib/polytexnic/postprocessors/html.rb:772:in `codelistings'
         5: from /var/lib/gems/2.7.0/gems/nokogiri-1.15.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
         4: from /var/lib/gems/2.7.0/gems/nokogiri-1.15.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
         3: from /var/lib/gems/2.7.0/gems/nokogiri-1.15.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
         2: from /var/lib/gems/2.7.0/gems/polytexnic-1.8.0/lib/polytexnic/postprocessors/html.rb:775:in `block in codelistings'
         1: from /var/lib/gems/2.7.0/gems/nokogiri-1.15.2-x86_64-linux/lib/nokogiri/xml/node.rb:149:in `add_child'
/var/lib/gems/2.7.0/gems/nokogiri-1.15.2-x86_64-linux/lib/nokogiri/xml/node.rb:1496:in `coerce': Requires a Node, NodeSet or String argument, and cannot accept a NilClass. (ArgumentError)
(You probably want to select a node from the Document with at() or search(), or create a new Node via Node.new().)
```

**Comment by mhartl** [comment]
Thanks for the report. The dependency listings were a little loose in both `polytexnic` and `softcover`, so I’ve updated them in both cases. See if running `gem install softcover -v 1.8.2` works for you.

The content in the `chapter.md` file you listed appears to be invalid, though, so producing an error may be expected behavior in this particular case. At the least, I believe you need a top-level (chapter) heading using `#` and a `\begin{codelisting}` command as well.
